/**
 * EduCanvas通用Agent领域契约的唯一公共入口。
 * @packageDocumentation
 */

export {
  assetDescriptorSchema,
  assetKindSchema,
  assetKinds,
  assetOriginSchema,
  assetOrigins,
  assetScopeSchema,
  assetScopes,
  assetStatusSchema,
  assetStatuses,
  assetVersionDescriptorSchema,
  assetVersionReferenceSchema,
  canTransitionAssetStatus,
  type AssetDescriptor,
  type AssetKind,
  type AssetOrigin,
  type AssetScope,
  type AssetStatus,
  type AssetVersionDescriptor,
  type AssetVersionReference,
} from './asset-contracts';

export {
  agentArtifactPartSchema,
  agentAssetPartSchema,
  agentMessageInputSchema,
  agentMessagePartSchema,
  agentMessageRoleSchema,
  agentMessageRoles,
  agentTextPartSchema,
  extractAgentMessageText,
  normalizeAgentMessageParts,
  referencedAssetKinds,
  referencedAssetVersions,
  type AgentArtifactPart,
  type AgentAssetPart,
  type AgentMessageInput,
  type AgentMessagePart,
  type AgentMessageRole,
  type AgentTextPart,
} from './message-contracts';

export {
  ModelGatewayInvocationError,
  modelAliasSchema,
  modelAliases,
  modelFinishReasonSchema,
  modelFinishReasons,
  modelMessageSchema,
  modelUsageSchema,
  normalizeModelGatewayError,
  normalizedModelErrorCodeSchema,
  normalizedModelErrorCodes,
  normalizedModelErrorSchema,
  providerCallMetadataSchema,
  speechTaskAliasSchema,
  speechTaskAliases,
  streamingTaskAliasSchema,
  streamingTaskAliases,
  structuredTaskAliasSchema,
  structuredTaskAliases,
  taskAliasSchema,
  taskAliases,
  turnModelEventSchema,
  turnModelPhaseSchema,
  turnModelPhases,
  type ModelAbortSignal,
  type ModelAlias,
  type ModelFinishReason,
  type ModelMessage,
  type ModelToolDefinition,
  type ModelToolResult,
  type ModelUsage,
  type NormalizedModelError,
  type ProviderCallMetadata,
  type SpeechTaskAlias,
  type StreamAgentTextRequest,
  type StreamingTaskAlias,
  type StreamTurnTextRequest,
  type StructuredTaskAlias,
  type TaskAlias,
  type TurnModelEvent,
  type TurnModelPhase,
} from './model-contracts';

export type {
  ModelGateway,
  SpeechAudioFormat,
  SpeechModelGateway,
  SpeechSynthesisRequest,
  SpeechSynthesisResult,
  StructuredModelGateway,
  StructuredModelRequest,
  StructuredModelResult,
  TurnModelGateway,
} from './model-gateway';

export {
  ObjectStorageError,
  isValidObjectKey,
  type ObjectStoragePort,
  type StoredObject,
} from './object-storage-contracts';
