/**
 * EduCanvas通用Agent领域契约的唯一公共入口。
 * @packageDocumentation
 */

export {
  assetDescriptorSchema,
  assetKindSchema,
  assetKinds,
  assetOriginSchema,
  assetOrigins,
  assetProcessorKindSchema,
  assetProcessorKinds,
  assetRepresentationKindSchema,
  assetRepresentationKinds,
  DEFAULT_REPRESENTATION_IDENTITY,
  representationIdentitySchema,
  representationProducerSchema,
  representationProducerVersionSchema,
  representationQualitySchema,
  representationQualityValues,
  representationVariantSchema,
  type RepresentationIdentity,
  type RepresentationQuality,
  assetScopeSchema,
  assetScopes,
  assetStatusSchema,
  assetStatuses,
  assetVersionDescriptorSchema,
  assetVersionReferenceSchema,
  canTransitionAssetStatus,
  type AssetDescriptor,
  type AssetKind,
  type AssetOrigin,
  type AssetProcessorKind,
  type AssetRepresentationKind,
  type AssetScope,
  type AssetStatus,
  type AssetVersionDescriptor,
  type AssetVersionReference,
} from './asset-contracts';

export {
  agentArtifactPartSchema,
  agentAssetPartSchema,
  agentMessageInputSchema,
  agentMessagePartSchema,
  agentMessageRoleSchema,
  agentMessageRoles,
  agentTextPartSchema,
  MAX_AGENT_MESSAGE_PARTS,
  extractAgentMessageText,
  normalizeAgentMessageParts,
  referencedAssetKinds,
  referencedAssetVersions,
  type AgentArtifactPart,
  type AgentAssetPart,
  type AgentMessageInput,
  type AgentMessagePart,
  type AgentMessageRole,
  type AgentTextPart,
} from './message-contracts';

export {
  ModelGatewayInvocationError,
  modelAliasSchema,
  modelAliases,
  modelFinishReasonSchema,
  modelFinishReasons,
  modelMessageSchema,
  modelInputPartSchema,
  modelMessageText,
  modelUsageSchema,
  normalizeModelGatewayError,
  normalizedModelErrorCodeSchema,
  normalizedModelErrorCodes,
  normalizedModelErrorSchema,
  providerCallMetadataSchema,
  speechTaskAliasSchema,
  speechTaskAliases,
  streamingTaskAliasSchema,
  streamingTaskAliases,
  structuredTaskAliasSchema,
  structuredTaskAliases,
  audioTranscriptionTaskAliasSchema,
  audioTranscriptionTaskAliases,
  embeddingTaskAliasSchema,
  embeddingTaskAliases,
  imageGenerationTaskAliasSchema,
  imageGenerationTaskAliases,
  taskAliasSchema,
  taskAliases,
  turnModelEventSchema,
  turnModelPhaseSchema,
  turnModelPhases,
  type AudioTranscriptionTaskAlias,
  type EmbeddingTaskAlias,
  type ImageGenerationTaskAlias,
  type ModelAbortSignal,
  type ModelAlias,
  type ModelFinishReason,
  type ModelMessage,
  type ModelInputPart,
  type ModelToolDefinition,
  type ModelToolResult,
  type ModelUsage,
  type NormalizedModelError,
  type ProviderCallMetadata,
  type SpeechTaskAlias,
  type StreamAgentTextRequest,
  type StreamingTaskAlias,
  type StreamTurnTextRequest,
  type StructuredTaskAlias,
  type TaskAlias,
  type TurnModelEvent,
  type TurnModelPhase,
} from './model-contracts';

export {
  CHARS_PER_TOKEN,
  TURN_USAGE_BUDGET_TEMPLATES,
  budgetBreachReasons,
  estimateTokensFromText,
  estimateUsageCostUsdCents,
  turnPricingPerMillionTokens,
  turnUsageBudgetSchema,
  usageMissing,
} from './turn-usage-budget';
export type {
  BudgetBreachReason,
  TurnUsageBudget,
  TurnUsageBudgetLedgerEntry,
  TurnUsageBudgetLedgerPort,
} from './turn-usage-budget';
export {
  RETRIEVAL_DEGRADATION_REASONS,
  embeddingGatewayErrorToRetrievalDegradation,
} from './retrieval-degradation';
export type { RetrievalDegradationReason } from './retrieval-degradation';
export type {
  AudioTranscriptionModelGateway,
  AudioTranscriptionRequest,
  AudioTranscriptionResult,
  EmbeddingDescriptor,
  EmbeddingModelGateway,
  EmbeddingPurpose,
  EmbeddingRequest,
  EmbeddingResult,
  GeneratedImage,
  ImageGenerationModelGateway,
  ImageGenerationRequest,
  ImageGenerationResult,
  ModelGateway,
  SpeechAudioFormat,
  SpeechModelGateway,
  SpeechSynthesisRequest,
  SpeechSynthesisResult,
  StructuredModelGateway,
  StructuredModelRequest,
  StructuredModelResult,
  SupportedAudioTranscriptionMimeType,
  SupportedGeneratedImageMimeType,
  SupportedGeneratedImageSize,
  TurnModelGateway,
} from './model-gateway';

export {
  PLATFORM_EMBEDDING_DIMENSIONS,
  embeddingPurposes,
  supportedAudioTranscriptionMimeTypes,
  supportedGeneratedImageMimeTypes,
  supportedGeneratedImageSizes,
} from './model-gateway';

export {
  agentModelRunStatuses,
  agentModelRunStatusSchema,
  type AgentModelRunLedgerPort,
  type AgentModelRunProviderResult,
  type AgentModelRunSnapshot,
  type AgentModelRunStatus,
  type AgentModelRunTerminalStatus,
  type CreateAgentModelRunInput,
} from './model-run-ledger';

export {
  isTurnApplicationTerminalEvent,
  turnApplicationCommandSchema,
  turnApplicationEventSchema,
  turnApplicationFailureCodeSchema,
  turnApplicationFailureCodes,
  turnApplicationProtocolVersion,
  validateTurnApplicationEventSequence,
  type TurnApplicationCommand,
  type TurnApplicationEvent,
  type TurnApplicationFailureCode,
} from './turn-application-contracts';

export {
  MAX_OPERATION_CONTINUATION_LEASE_MS,
  MIN_OPERATION_CONTINUATION_LEASE_MS,
  OPERATION_CONTINUATION_TASK,
  createOperationContinuationInputSchema,
  prepareToolApprovalIntentInputSchema,
  operationContinuationAdapterSourceSchema,
  operationContinuationAdapterSources,
  operationContinuationProtocolVersion,
  operationContinuationSnapshotSchema,
  operationContinuationStatusSchema,
  operationContinuationStatuses,
  operationContinuationWorkSchema,
  toolApprovalIntentProtocolVersion,
  toolApprovalIntentSnapshotSchema,
  toolApprovalIntentStatusSchema,
  toolApprovalIntentStatuses,
  type CreateOperationContinuationInput,
  type OperationContinuationAdapterSource,
  type OperationContinuationPort,
  type OperationContinuationSnapshot,
  type OperationContinuationStatus,
  type OperationContinuationTerminalStatus,
  type OperationContinuationWork,
  type PrepareToolApprovalIntentInput,
  type ToolApprovalIntentPort,
  type ToolApprovalIntentSnapshot,
  type ToolApprovalIntentStatus,
} from './operation-continuation';

export {
  MAX_OPERATION_CONTINUATION_RECOVERY_BATCH,
  operationContinuationRecoveryInputSchema,
  operationContinuationRecoveryResultSchema,
  type OperationContinuationRecoveryInput,
  type OperationContinuationRecoveryPort,
  type OperationContinuationRecoveryResult,
} from './operation-continuation-recovery';

export { w3cTraceCarrierSchema, type W3cTraceCarrier } from './trace-carrier';

export type {
  AgentTurnContextLedgerPort,
  AgentTurnContextMaterial,
  AgentTurnContextSnapshot,
} from './turn-context-ledger';

export {
  agentToolCallStatusSchema,
  agentToolCallStatuses,
  agentToolEffectSchema,
  agentToolExposureSchema,
  type AgentToolAuditValueSummary,
  type AgentToolCallLedgerPort,
  type AgentToolCallSnapshot,
  type AgentToolCallStatus,
  type AgentToolCallTerminalStatus,
  type AgentToolEffect,
  type AgentToolExposure,
  type CreateAgentToolCallInput,
} from './tool-call-ledger';

export {
  toolEffectLedgerStatuses,
  type ToolEffectLedgerPort,
  type ToolEffectLedgerSnapshot,
  type ToolEffectLedgerStatus,
  type ToolEffectLedgerTerminalStatus,
} from './tool-effect-ledger';

export {
  toolEffectReconciliationResolutions,
  toolEffectReconciliationSources,
  type ToolEffectReconciliationPort,
  type ToolEffectReconciliationResolution,
  type ToolEffectReconciliationSnapshot,
  type ToolEffectReconciliationSource,
} from './tool-effect-reconciliation';

export {
  ObjectStorageError,
  isValidObjectKey,
  type ObjectStoragePort,
  type StoredObject,
} from './object-storage-contracts';

export type {
  WebRuntimeArtifactVersionReference,
  WebRuntimeEvent,
  WebRuntimeExecutionRequest,
  WebRuntimeFailureCode,
  WebRuntimePort,
  WebRuntimeResourceLimits,
} from './web-runtime-port';

export {
  MAX_PCM_CHUNK_BYTES,
  MAX_STREAMING_TRANSCRIPTION_TEXT_LENGTH,
  STREAMING_TRANSCRIPTION_CHANNELS,
  STREAMING_TRANSCRIPTION_PCM_ENCODING,
  STREAMING_TRANSCRIPTION_SAMPLE_RATE_HZ,
  StreamingTranscriptionStateError,
  isStreamingTranscriptionTerminalEvent,
  streamingTranscriptionEventSchema,
  streamingTranscriptionFailureCodeSchema,
  streamingTranscriptionFailureCodes,
  streamingTranscriptionPcmChunkSchema,
  streamingTranscriptionProtocolVersion,
  validateStreamingTranscriptionEventSequence,
  type StreamingTranscriptionEvent,
  type StreamingTranscriptionFailureCode,
  type StreamingTranscriptionPcmChunk,
} from './streaming-transcription-contracts';

export type {
  StreamingTranscriptionGateway,
  StreamingTranscriptionRequest,
  StreamingTranscriptionSession,
} from './streaming-transcription-port';

export {
  STREAMING_SPEECH_CHANNELS,
  STREAMING_SPEECH_ENCODING,
  STREAMING_SPEECH_SAMPLE_RATE_HZ,
  type StreamingSpeechEvent,
  type StreamingSpeechGateway,
  type StreamingSpeechRequest,
} from './streaming-speech-port';

export {
  applyStreamingTranscriptionEvent,
  createStreamingTranscriptionSnapshot,
  type StreamingTranscriptionEventType,
  type StreamingTranscriptionSegmentState,
  type StreamingTranscriptionSnapshot,
} from './streaming-transcription-reducer';

export {
  STREAMING_TRANSCRIPTION_TAIL_SILENCE_BYTES,
  STREAMING_TRANSCRIPTION_TAIL_SILENCE_SECONDS,
  applyStreamingTranscriptionCancel,
  applyStreamingTranscriptionChunk,
  applyStreamingTranscriptionEndpoint,
  applyStreamingTranscriptionFinish,
  createStreamingSegmentationSnapshot,
  type StreamingSegmentationPhase,
  type StreamingSegmentationSnapshot,
  type StreamingSegmentationTailChunk,
} from './streaming-transcription-segmentation-policy';

export {
  streamingTranscriptionClientMessageSchema,
  streamingTranscriptionServerMessageSchema,
  toStreamingTranscriptionPcmChunk,
  validateStreamingTranscriptionClientMessageSequence,
  validateStreamingTranscriptionServerMessageSequence,
  type StreamingTranscriptionClientMessage,
  type StreamingTranscriptionClientMessageType,
  type StreamingTranscriptionServerMessage,
} from './streaming-transcription-envelope';

export {
  StreamingTranscriptionClientMessageSequenceTracker,
  StreamingTranscriptionEventSequenceTracker,
} from './streaming-transcription-sequence-tracker';

export {
  canTransitionExperimentRunStatus,
  experimentDependencySchema,
  experimentFailureCodeSchema,
  experimentFailureCodes,
  experimentInputMountSchema,
  experimentLogEntrySchema,
  experimentOutputArtifactSchema,
  experimentProvenanceSchema,
  experimentResourceBudgetSchema,
  experimentRunEventSchema,
  experimentRunResultSchema,
  experimentRunSchema,
  experimentRunStatusSchema,
  experimentRunStatuses,
  experimentRunTerminalStatusSchema,
  experimentRunTerminalStatuses,
  MAX_EXPERIMENT_DURATION_MS,
  MAX_EXPERIMENT_LOG_BYTES,
  MAX_EXPERIMENT_MEMORY_MIB,
  MAX_EXPERIMENT_OUTPUT_BYTES,
  MAX_EXPERIMENT_OUTPUT_FILES,
  MAX_EXPERIMENT_PROCESSES,
  MAX_EXPERIMENT_STDOUT_BYTES,
  rejectsCustomImageOrShell,
  rejectsGpuCapability,
  rejectsNetworkCapability,
  type ExperimentDependency,
  type ExperimentFailureCode,
  type ExperimentInputMount,
  type ExperimentLogEntry,
  type ExperimentOutputArtifact,
  type ExperimentProvenance,
  type ExperimentResourceBudget,
  type ExperimentRun,
  type ExperimentRunEvent,
  type ExperimentRunResult,
  type ExperimentRunStatus,
  type ExperimentRunTerminalStatus,
  type ExperimentRuntimePort,
} from './experiment-runtime-port';

export {
  MAX_AUTHORIZED_TERMS,
  MAX_CONTEXT_WORDS_PER_TERM,
  MAX_CONTEXT_WORD_LENGTH,
  MAX_EDIT_DISTANCE,
  MAX_REPLACEMENTS,
  MAX_TERM_LENGTH,
  MAX_TRANSCRIPT_LENGTH,
  TranscriptTermCorrectionError,
  applyTranscriptReplacements,
  authorizedTermSchema,
  correctTranscript,
  transcriptCasePolicies,
  transcriptCasePolicySchema,
  transcriptCorrectionErrorCodes,
  transcriptCorrectionErrorCodeSchema,
  transcriptReplacementSchema,
  transcriptTermCorrectionInputSchema,
  transcriptTermCorrectionProtocolVersion,
  transcriptTermCorrectionResultSchema,
  transcriptUnchangedReasonSchema,
  transcriptUnchangedReasons,
  type AuthorizedTerm,
  type TranscriptCasePolicy,
  type TranscriptCorrectionErrorCode,
  type TranscriptReplacement,
  type TranscriptTermCorrectionInput,
  type TranscriptTermCorrectionResult,
  type TranscriptUnchangedReason,
} from './transcript-term-correction';
