ALTER TABLE "model_runs" DROP CONSTRAINT "model_runs_teaching_turn_shape_check";--> statement-breakpoint
ALTER TABLE "model_runs" DROP CONSTRAINT "model_runs_attempt_check";--> statement-breakpoint
ALTER TABLE "model_runs" ALTER COLUMN "session_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "model_runs" ADD COLUMN "agent_operation_id" uuid;--> statement-breakpoint
ALTER TABLE "model_runs" ADD COLUMN "conversation_message_id" uuid;--> statement-breakpoint
ALTER TABLE "model_runs" ADD CONSTRAINT "model_runs_agent_operation_id_agent_operations_id_fk" FOREIGN KEY ("agent_operation_id") REFERENCES "public"."agent_operations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "model_runs" ADD CONSTRAINT "model_runs_conversation_message_id_conversation_messages_id_fk" FOREIGN KEY ("conversation_message_id") REFERENCES "public"."conversation_messages"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "model_runs_agent_operation_idx" ON "model_runs" USING btree ("agent_operation_id","created_at","id");--> statement-breakpoint
ALTER TABLE "model_runs" ADD CONSTRAINT "model_runs_operation_shape_check" CHECK (("model_runs"."operation_kind" = 'teaching_turn' and "model_runs"."session_id" is not null and "model_runs"."agent_operation_id" is null and "model_runs"."assistant_message_id" is not null and "model_runs"."conversation_message_id" is null and "model_runs"."turn_id" is not null and "model_runs"."operation_id" = "model_runs"."turn_id" and "model_runs"."task_alias" = 'teaching.turn') or ("model_runs"."operation_kind" = 'agent_turn' and "model_runs"."session_id" is null and "model_runs"."agent_operation_id" is not null and "model_runs"."operation_id" = "model_runs"."agent_operation_id" and "model_runs"."assistant_message_id" is null and "model_runs"."conversation_message_id" is not null and "model_runs"."turn_id" is null));--> statement-breakpoint
ALTER TABLE "model_runs" ADD CONSTRAINT "model_runs_phase_check" CHECK ("model_runs"."phase" in ('answer', 'synthesis'));--> statement-breakpoint
ALTER TABLE "model_runs" ADD CONSTRAINT "model_runs_text_check" CHECK (char_length("model_runs"."trace_id") between 1 and 128 and "model_runs"."task_alias" in ('agent.turn', 'teaching.turn') and "model_runs"."model_alias" in ('primary', 'fast', 'structured', 'speech') and char_length("model_runs"."prompt_version") between 1 and 128 and "model_runs"."prompt_hash" ~ '^[a-f0-9]{64}$' and ("model_runs"."provider" is null or char_length("model_runs"."provider") between 1 and 128) and ("model_runs"."provider_model_id" is null or char_length("model_runs"."provider_model_id") between 1 and 256) and ("model_runs"."model_revision" is null or char_length("model_runs"."model_revision") between 1 and 256) and ("model_runs"."provider_response_id" is null or char_length("model_runs"."provider_response_id") between 1 and 512) and ("model_runs"."system_fingerprint" is null or char_length("model_runs"."system_fingerprint") between 1 and 512) and ("model_runs"."finish_reason" is null or "model_runs"."finish_reason" in ('stop', 'tool_calls', 'length', 'content_filter', 'cancelled', 'error', 'other')) and ("model_runs"."error_code" is null or "model_runs"."error_code" ~ '^[a-z][a-z0-9._:-]{0,127}$'));--> statement-breakpoint
ALTER TABLE "model_runs" ADD CONSTRAINT "model_runs_attempt_check" CHECK ("model_runs"."attempt" between 1 and 100);