/**
 * EduCanvas教学领域核心的唯一公共入口。
 * @packageDocumentation
 */

export {
  assessmentExitDecisionSchema,
  assessmentExitDecisions,
  beginInterruption,
  evaluateTransition,
  resumeInterruption,
  resolveTransitionCandidate,
  selectInitialState,
  teachingTransitionCandidateSignalSchema,
  teachingTransitionCandidateSignals,
  teachingStateSchema,
  teachingStates,
  transitionRequestSchema,
  type AssessmentExitDecision,
  type CandidateTransitionResolution,
  type InterruptionResult,
  type TeachingSessionCursor,
  type TeachingState,
  type TeachingTransitionCandidateSignal,
  type TransitionEvaluation,
  type TransitionRejectionCode,
  type TransitionRequest,
} from './state-machine';
export {
  LearningProjectionError,
  createDefaultLearningProjectionConfig,
  createLearningProjection,
  learningProjectionConfigSchema,
  learningProjectionSeedSchema,
  nextNodeCourseConfigSchema,
  projectLearningEvent,
  projectMasterySnapshot,
  recommendNextNode,
  recommendNextNodeInputSchema,
  replayLearningEvents,
  type LearningProjection,
  type LearningProjectionConfig,
  type LearningProjectionErrorCode,
  type LearningProjectionSeed,
  type NextNodeCourseConfig,
  type NextNodeRecommendation,
  type RecommendNextNodeInput,
} from './learning-projection';
export {
  DEFAULT_MASTERY_POLICY_VERSION,
  assessmentEvidenceSchema,
  assessmentReasonSchema,
  assessmentReasons,
  calculateMastery,
  decideAssessmentExit,
  defaultMasteryConfig,
  getReviewIntervalDays,
  masteryConfigSchema,
  masteryInputSchema,
  misconceptionTagSchema,
  misconceptionTags,
  type AssessmentEvidence,
  type AssessmentExit,
  type AssessmentReason,
  type MasteryCalculation,
  type MasteryConfig,
  type MasteryInput,
  type MisconceptionTag,
} from './mastery';
export {
  DOMAIN_EVENT_SCHEMA_VERSION,
  domainEventSources,
  domainLearningEventSchema,
  domainLearningEventTypes,
  type DomainLearningEvent,
  type DomainLearningEventType,
} from './domain-events';
export {
  defaultToolPolicy,
  isToolAllowed,
  teachingToolSchema,
  teachingTools,
  type TeachingTool,
} from './tools';
export {
  ModelGatewayInvocationError,
  modelAliasSchema,
  modelAliases,
  modelFinishReasonSchema,
  modelFinishReasons,
  modelMessageSchema,
  modelUsageSchema,
  normalizeModelGatewayError,
  normalizedModelErrorCodeSchema,
  normalizedModelErrorCodes,
  normalizedModelErrorSchema,
  providerCallMetadataSchema,
  streamingTaskAliasSchema,
  streamingTaskAliases,
  structuredTaskAliasSchema,
  structuredTaskAliases,
  taskAliasSchema,
  taskAliases,
  turnModelEventSchema,
  turnModelPhaseSchema,
  turnModelPhases,
  type ModelAlias,
  type ModelAbortSignal,
  type ModelFinishReason,
  type ModelMessage,
  type ModelToolDefinition,
  type ModelToolResult,
  type ModelUsage,
  type NormalizedModelError,
  type ProviderCallMetadata,
  type StreamAgentTextRequest,
  type StreamingTaskAlias,
  type StreamTurnTextRequest,
  type StructuredTaskAlias,
  type TaskAlias,
  type TurnModelEvent,
  type TurnModelPhase,
} from './model-contracts';
export {
  K12_MAX_INPUT_CODE_POINTS,
  K12_MAX_INPUT_UTF8_BYTES,
  K12_SAFETY_DETECTOR_VERSION,
  K12_SAFETY_POLICY_VERSION,
  evaluateTeachingInput,
  evaluateTeachingOutputText,
  teachingSafetyActions,
  teachingSafetyCategories,
  teachingSafetyDecisionSchema,
  teachingSafetyLocales,
  teachingSafetyPhases,
  teachingSafetyPolicyCodes,
  type TeachingSafetyAction,
  type TeachingSafetyCategory,
  type TeachingSafetyDecision,
  type TeachingSafetyEvaluation,
  type TeachingSafetyLocale,
  type TeachingSafetyPhase,
  type TeachingSafetyPolicyCode,
  type TeachingSafetyPublicResponse,
} from './safety-policy';
export {
  defaultTeachingPreferences,
  learnerAgeBandSchema,
  learnerAdaptationPolicySchema,
  learnerAgeBands,
  learnerDeclarationSourceSchema,
  learnerDeclarationSources,
  learnerGradeBandSchema,
  learnerGradeBands,
  learnerProfileDeclarationSchema,
  resolveLearnerAdaptationPolicy,
  teachingPreferencesSchema,
  type LearnerAdaptationPolicy,
  type LearnerAgeBand,
  type LearnerDeclarationSource,
  type LearnerGradeBand,
  type LearnerProfileDeclaration,
  type TeachingPreferences,
} from './learner-profile';
export {
  diagnosticObjectiveStatuses,
  diagnosticQuestionDefinitionSchema,
  diagnosticSubmissionSchema,
  gradeDiagnostic,
  learningObjectiveDefinitionSchema,
  projectPublicDiagnostic,
  publicDiagnosticSchema,
  studyCourseDefinitionSchema,
  type DiagnosticGradingDecision,
  type DiagnosticObjectiveProgress,
  type DiagnosticObjectiveStatus,
  type DiagnosticQuestionDefinition,
  type DiagnosticSubmission,
  type GradedDiagnostic,
  type GradedDiagnosticAnswer,
  type LearningObjectiveDefinition,
  type PublicDiagnostic,
  type StudyCourseDefinition,
} from './study-plan';
export type {
  EventStore,
  KnowledgeEvidence,
  KnowledgeRetrievalRequest,
  KnowledgeRetriever,
  LessonSessionSnapshot,
  MasteryRepository,
  MasterySnapshot,
  ModelGateway,
  SaveMasteryInput,
  SessionRepository,
  StructuredModelGateway,
  StructuredModelRequest,
  StructuredModelResult,
  TeachingTransaction,
  TeachingUnitOfWork,
  TurnModelGateway,
  UpdateSessionStateInput,
} from './ports';
